set_property SRC_FILE_INFO {cfile:D:/Documents/ProgH-Practica/PROGH2/Practicum_01/Practicum_01.srcs/constrs_1/new/constraints.xdc rfile:../../../Practicum_01.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports q]
