set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports blue]
set_property IOSTANDARD LVCMOS33 [get_ports clk25]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN J18 [get_ports blue]
set_property PACKAGE_PIN N19 [get_ports red]
set_property PACKAGE_PIN D17 [get_ports green]
set_property PACKAGE_PIN W5 [get_ports clk25]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports blueSwitch]
set_property IOSTANDARD LVCMOS33 [get_ports redSwitch]
set_property IOSTANDARD LVCMOS33 [get_ports greenSwitch]
set_property PACKAGE_PIN R2 [get_ports redSwitch]
set_property PACKAGE_PIN U1 [get_ports blueSwitch]
set_property PACKAGE_PIN T1 [get_ports greenSwitch]
