# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148.xci
# IP: The module: 'Clk_148' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148.xci
# IP: The module: 'Clk_148' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlgheuve/Documents/Werkmap/2018-2019/Periode 3/PROGH2/Opdrachten/Uiterkingen opdrachten/Vivado projecten/VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/Clk_148/Clk_148_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
