set_property PACKAGE_PIN C17 [get_ports psclk]
set_property PACKAGE_PIN B17 [get_ports psdin]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports psdin]
set_property IOSTANDARD LVCMOS33 [get_ports psclk]

set_property PACKAGE_PIN U16 [get_ports {PS2outLed[0]}]
set_property PACKAGE_PIN E19 [get_ports {PS2outLed[1]}]
set_property PACKAGE_PIN U19 [get_ports {PS2outLed[2]}]
set_property PACKAGE_PIN V19 [get_ports {PS2outLed[3]}]
set_property PACKAGE_PIN W18 [get_ports {PS2outLed[4]}]
set_property PACKAGE_PIN U15 [get_ports {PS2outLed[5]}]
set_property PACKAGE_PIN U14 [get_ports {PS2outLed[6]}]
set_property PACKAGE_PIN V14 [get_ports {PS2outLed[7]}]
set_property PACKAGE_PIN V13 [get_ports {PS2outLed[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2outLed[2]}]

set_property PACKAGE_PIN B18 [get_ports UartTX]
set_property PACKAGE_PIN A18 [get_ports UartRX]

