# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/djans/Documents/ProgH-Practica/PROGH2/Practicum_01/Practicum_01.srcs/sources_1/ip/BertErnie8K/BertErnie8K.xci
# IP: The module: 'BertErnie8K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/djans/Documents/ProgH-Practica/PROGH2/Practicum_01/Practicum_01.srcs/sources_1/ip/BertErnie8K/BertErnie8K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BertErnie8K'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/djans/Documents/ProgH-Practica/PROGH2/Practicum_01/Practicum_01.srcs/sources_1/ip/BertErnie8K/BertErnie8K.xci
# IP: The module: 'BertErnie8K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/djans/Documents/ProgH-Practica/PROGH2/Practicum_01/Practicum_01.srcs/sources_1/ip/BertErnie8K/BertErnie8K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BertErnie8K'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
