# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/Notecontrol/Notecontrol.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol || ORIG_REF_NAME==Notecontrol} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_axi_gpio_0_0/Notecontrol_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_axi_gpio_0_0 || ORIG_REF_NAME==Notecontrol_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_clk_wiz_0_0/Notecontrol_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_clk_wiz_0_0 || ORIG_REF_NAME==Notecontrol_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_axi_uartlite_0_0/Notecontrol_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_axi_uartlite_0_0 || ORIG_REF_NAME==Notecontrol_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_microblaze_0_1/Notecontrol_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_microblaze_0_1 || ORIG_REF_NAME==Notecontrol_microblaze_0_1} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_mdm_1_0/Notecontrol_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_mdm_1_0 || ORIG_REF_NAME==Notecontrol_mdm_1_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_rst_clk_wiz_0_100M_0/Notecontrol_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Notecontrol_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_microblaze_0_axi_periph_0/Notecontrol_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Notecontrol_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_xbar_0/Notecontrol_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_xbar_0 || ORIG_REF_NAME==Notecontrol_xbar_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_dlmb_v10_0/Notecontrol_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_dlmb_v10_0 || ORIG_REF_NAME==Notecontrol_dlmb_v10_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_ilmb_v10_0/Notecontrol_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_ilmb_v10_0 || ORIG_REF_NAME==Notecontrol_ilmb_v10_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_dlmb_bram_if_cntlr_0/Notecontrol_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Notecontrol_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_ilmb_bram_if_cntlr_0/Notecontrol_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Notecontrol_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Notecontrol/ip/Notecontrol_lmb_bram_0/Notecontrol_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Notecontrol_lmb_bram_0 || ORIG_REF_NAME==Notecontrol_lmb_bram_0} -quiet] -quiet

# XDC: bd/Notecontrol/Notecontrol_ooc.xdc
