# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache C:/Users/Kayne/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-17156-LAPTOP-HRAQ4RRP/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.cache/wt [current_project]
set_property parent.project_path D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/hdl/Notecontrol_wrapper.vhd
  D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/new/PS2Reader.vhd
  D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/new/NoteviewTop.vhd
}
add_files D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/Notecontrol.bd
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_gpio_0_0/Notecontrol_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_gpio_0_0/Notecontrol_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_gpio_0_0/Notecontrol_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_clk_wiz_0_0/Notecontrol_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_clk_wiz_0_0/Notecontrol_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_clk_wiz_0_0/Notecontrol_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_uartlite_0_0/Notecontrol_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_uartlite_0_0/Notecontrol_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_axi_uartlite_0_0/Notecontrol_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_microblaze_0_1/Notecontrol_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_microblaze_0_1/Notecontrol_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_microblaze_0_1/Notecontrol_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_mdm_1_0/Notecontrol_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_mdm_1_0/Notecontrol_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_rst_clk_wiz_0_100M_0/Notecontrol_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_rst_clk_wiz_0_100M_0/Notecontrol_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_rst_clk_wiz_0_100M_0/Notecontrol_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_xbar_0/Notecontrol_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_dlmb_v10_0/Notecontrol_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_dlmb_v10_0/Notecontrol_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_ilmb_v10_0/Notecontrol_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_ilmb_v10_0/Notecontrol_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_dlmb_bram_if_cntlr_0/Notecontrol_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_ilmb_bram_if_cntlr_0/Notecontrol_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/ip/Notecontrol_lmb_bram_0/Notecontrol_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/sources_1/bd/Notecontrol/Notecontrol_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files D:/FPGA/ProgH-Practicum/PROGH2/EindopdrachtMicroblaze/EindopdrachtMicroblaze.srcs/constrs_1/new/constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top NoteviewTop -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NoteviewTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NoteviewTop_utilization_synth.rpt -pb NoteviewTop_utilization_synth.pb"
