# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/ProgH-Practicum/PROGH2/LES3_VGA_HD_timing_issues_smly_K/LES3_VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/ProgH-Practicum/PROGH2/LES3_VGA_HD_timing_issues_smly_K/LES3_VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA/ProgH-Practicum/PROGH2/LES3_VGA_HD_timing_issues_smly_K/LES3_VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/ProgH-Practicum/PROGH2/LES3_VGA_HD_timing_issues_smly_K/LES3_VGA_HD_timing_issues_smly/VGA_HD.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
